### ISSUE TITLE
Unable to post review: TypeError: Cannot read property 'insertOne' of undefined

### ISSUE THREAD

**Issue by quochuydo95** [beaucarnes/restaurant-reviews#8]
Try to make a post request to add a review return with: 
_Unable to post review: TypeError: Cannot read property 'insertOne' of undefined_

**Comment by kypertirost** [comment]
Most likely you are missing this line. https://github.com/beaucarnes/restaurant-reviews/blob/master/backend/index.js#L24

**Comment by shlomohal84** [comment]
thank you kind sir!

**Comment by kidneybeans007** [comment]
Thank you @kypertirost been trying to fix this for a couple hrs looking through the code.  Novice javascript coder here.  much appreciated\

**Comment by adam-weiler** [comment]
I was following this tutorial on YT and ran into the same error. I googled the error and happened to find this post connected to the same project. Thanks! 😀

**Comment by Razan110** [comment]
I have the same error but in different YT tatourial (movie reviews) i do have this line added but somehow i got this error when i try to post a review  "await ReviewsDAO.injectDB(client)", TypeError: Cannot read properties of undefined (reading 'insertOne').
